version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-anime
    restart: always
    environment:
      POSTGRES_USER: animesAPI
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_animes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U animesAPI -d db_animes"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: anime-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_animes
      SPRING_DATASOURCE_USERNAME: animesAPI
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"

volumes:
  postgres_data:
